name: Publie une image de conteneur OpenXchange de test

on:
  push:
    paths: [ oxtest/** ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ox-test

jobs:
  Deploy:
    name: Crée l'image et publie
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Récupère le numéro de version
        run: |
          version=$(cat oxtest/VERSION)
          echo "container_version=${container_version}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        id: login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Pousse une image Docker'
        uses: docker/build-push-action@v5
        with:
          context: oxtest
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: |  
            ghcr.io/${{ github.repository }}/oxtest:latest
            ghcr.io/${{ github.repository }}/oxtest:${{ github.sha }}
            ghcr.io/${{ github.repository }}/oxtest:${{ env.container_version }}
